#!/usr/bin/env python3
"""Generate ollama/Modelfile from the Task that actually runs.

Why generate it instead of writing it by hand: the reviewer's system prompt lives
in `CodeReviewTask.system_prompt()`. If a published Ollama model hard-codes a copy,
the two drift the first time the prompt is tuned, and the published model quietly
stops matching the repo it claims to come from. Generating it means the copy can't
be stale, and `--check` makes CI fail if someone edits one without the other.

  python scripts/build_modelfile.py            # write ollama/Modelfile
  python scripts/build_modelfile.py --check    # exit 1 if it's out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from selfevolve.config import Config  # noqa: E402
from selfevolve.tasks.code_review import CodeReviewTask  # noqa: E402

OUT = ROOT / "ollama" / "Modelfile"

HEADER = """\
# Generated by scripts/build_modelfile.py — do not edit by hand.
# Regenerate with:  python scripts/build_modelfile.py
#
# A qwen3:8b variant preloaded with the selfevolve reviewer's system prompt and
# decoding settings, so `ollama run <you>/selfevolve-reviewer` behaves like the
# agent's review step without installing anything.
#
# Note: selfevolve itself sends its own system message on every request, which
# takes precedence over the SYSTEM baked in here. This model is a convenience for
# using the reviewer directly from the Ollama CLI or any other client — it is not
# what makes the agent work, and switching it out does not change the agent's
# behaviour. The learning loop lives in the application, not in the weights.
"""


def render() -> str:
    cfg = Config()
    task = CodeReviewTask()
    prompt = task.system_prompt().strip()
    return (
        f"{HEADER}\n"
        f"FROM {cfg.llm_model}\n\n"
        f"# Low temperature: review comments should be reproducible, not creative.\n"
        f"PARAMETER temperature 0.2\n"
        f"PARAMETER num_ctx 8192\n\n"
        f'SYSTEM """{prompt}"""\n'
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify without writing")
    args = ap.parse_args()

    content = render()
    OUT.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not OUT.exists():
            print(f"{OUT.relative_to(ROOT)} is missing — run: python scripts/build_modelfile.py")
            return 1
        if OUT.read_text(encoding="utf-8") != content:
            print(
                f"{OUT.relative_to(ROOT)} is out of date with CodeReviewTask.system_prompt().\n"
                "Regenerate it:  python scripts/build_modelfile.py"
            )
            return 1
        print(f"{OUT.relative_to(ROOT)} is in sync with the task.")
        return 0

    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
